# Generated by Django 5.1 on 2024-08-14 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_notification_is_read_alter_notification_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
