# Generated by Django 5.1 on 2024-08-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_notification_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
